# Generated by Django 5.0.2 on 2024-11-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notlar', '0003_rename_description_note_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
