# Generated by Django 5.0.2 on 2024-11-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notlar', '0004_note_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='pdf',
        ),
    ]
