# Generated by Django 5.0.2 on 2024-11-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notlar', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
