# Generated by Django 5.0.2 on 2024-11-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notlar', '0007_profile_bio_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
