# Generated by Django 5.0.2 on 2024-11-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notlar', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
