# Generated by Django 5.0.2 on 2024-11-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notlar', '0010_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
