# Generated by Django 5.0.2 on 2024-12-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notlar', '0011_note_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ders_kategori',
            field=models.CharField(blank=True, choices=[('elektrik_makinalari', 'Elektrik Makineleri'), ('sinyaller_sistemler', 'Sinyaller ve Sistemler'), ('devre_teorisi', 'Devre Teorisi'), ('elektronik', 'Elektronik'), ('kontrol_sistemleri', 'Kontrol Sistemleri'), ('enerji_sistemleri', 'Enerji Sistemleri'), ('elektrik_guc_sistemleri', 'Elektrik Güç Sistemleri'), ('dijital_elektronik', 'Dijital Elektronik'), ('mikrodenetleyiciler', 'Mikrodenetleyiciler'), ('haberlesme_sistemleri', 'Haberleşme Sistemleri'), ('elektromanyetik_alanlar', 'Elektromanyetik Alanlar'), ('endustriyel_uygulamalar', 'Endüstriyel Uygulamalar'), ('yenilenebilir_enerji', 'Yenilenebilir Enerji Sistemleri'), ('robotik', 'Robotik'), ('otomasyon', 'Otomasyon Sistemleri'), ('yapay_zeka', 'Yapay Zeka'), ('bilgisayar_muhendisligi', 'Bilgisayar Mühendisliği'), ('sensör_teknolojileri', 'Sensör Teknolojileri'), ('guc_elektronigi', 'Güç Elektroniği'), ('optik_iletime', 'Optik İletişim Sistemleri'), ('motor_kontrol', 'Motor Kontrol Sistemleri'), ('isaret_isleme', 'İşaret İşleme')], max_length=50, null=True, verbose_name='Ders Kategori'),
        ),
        migrations.AddField(
            model_name='note',
            name='kategori',
            field=models.CharField(choices=[('genel', 'Genel'), ('ders', 'Ders'), ('is', 'İş'), ('spor', 'Spor'), ('teknoloji', 'Teknoloji'), ('saglik', 'Sağlık'), ('egitim', 'Eğitim')], default='genel', max_length=50, verbose_name='Kategori'),
        ),
    ]
